Remove parallel2 flag from Allrun scripts

diff --git a/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/rgs2D_Coarse/Allrun b/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/rgs2D_Coarse/Allrun
--- a/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/rgs2D_Coarse/Allrun
+++ b/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/rgs2D_Coarse/Allrun
@@ -72,84 +72,47 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
     # Create 2D mesh
     runApplication extrudeMesh || exit 1
 
-    if [[ $flagParallel2 -eq 1 ]]; then
+    # Create new topoSets
+    runApplication \
+        setSet -noVTK -batch 'system/setSetBatch' || exit 1
 
-        # TODO?
-        echo "Parallel 2 not supported!"
-        exit 1
+    # Create new patches
+    runApplication \
+        createPatch -overwrite || exit 1
 
-    else
+    # Change dictionaries
+    runApplication \
+        changeDictionary || exit 1
 
-        # Create new topoSets
-        runApplication \
-            setSet -noVTK -batch 'system/setSetBatch' || exit 1
+    # Create backup of topoSets
+    rm "constant/polyMesh/sets/"*"_old" > /dev/null 2>&1
+    mkdir 'constant/polyMesh/sets/bak'
+    cp 'constant/polyMesh/sets/'* \
+        'constant/polyMesh/sets/bak/' \
+        > /dev/null 2>&1
 
-        # Create new patches
-        runApplication \
-            createPatch -overwrite || exit 1
+    # Create meshes
+    for n in $(eval echo "{1..$regionlist_splitn}"); do
 
-        # Change dictionaries
-        runApplication \
-            changeDictionary || exit 1
+        regionlist=$(eval echo \$regionlist_split$n)
 
-        # Create backup of topoSets
-        rm "constant/polyMesh/sets/"*"_old" > /dev/null 2>&1
-        mkdir 'constant/polyMesh/sets/bak'
-        cp 'constant/polyMesh/sets/'* \
-           'constant/polyMesh/sets/bak/' \
-           > /dev/null 2>&1
+        # Remove all topoSets
+        rm 'constant/polyMesh/sets/'* > /dev/null 2>&1
 
-        # Create meshes
-        for n in $(eval echo "{1..$regionlist_splitn}"); do
+        # Restore faceSets
+        cp 'constant/polyMesh/sets/bak/faceSet_'* \
+            'constant/polyMesh/sets/' \
+            > /dev/null 2>&1
 
-            regionlist=$(eval echo \$regionlist_split$n)
+        # Restore pointSets
+        cp 'constant/polyMesh/sets/bak/pointSet_'* \
+            'constant/polyMesh/sets/' \
+            > /dev/null 2>&1
 
-            # Remove all topoSets
-            rm 'constant/polyMesh/sets/'* > /dev/null 2>&1
-
-            # Restore faceSets
-            cp 'constant/polyMesh/sets/bak/faceSet_'* \
-                'constant/polyMesh/sets/' \
-                > /dev/null 2>&1
-
-            # Restore pointSets
-            cp 'constant/polyMesh/sets/bak/pointSet_'* \
-                'constant/polyMesh/sets/' \
-                > /dev/null 2>&1
-
-            # Restore cellSets for this step of splitMeshRegions
-            for region in $regionlist; do
-                cp "constant/polyMesh/sets/bak/cellSet_$region" \
-                'constant/polyMesh/sets/' || exit 1
-            done
-
-            # Remove all zones
-            rm -f 'constant/polyMesh/cellZones' > /dev/null 2>&1
-            rm -f 'constant/polyMesh/faceZones' > /dev/null 2>&1
-            rm -f 'constant/polyMesh/pointZones' > /dev/null 2>&1
-
-            # Create zones for restored topoSets
-            runApplication -l "log.setsToZones.$n" \
-                setsToZones || exit 1
-
-            # Remove topoSet prefixes from topoZones
-            sed -i 's/cellSet_//g' 'constant/polyMesh/cellZones' > /dev/null 2>&1
-            sed -i 's/faceSet_//g' 'constant/polyMesh/faceZones' > /dev/null 2>&1
-            sed -i 's/pointSet_//g' 'constant/polyMesh/pointZones' > /dev/null 2>&1
-
-            # Restore all topoSets
-            cp 'constant/polyMesh/sets/bak/'* \
-                'constant/polyMesh/sets/' \
-                > /dev/null 2>&1
-
-            # Split regions
-            runApplication -l "log.splitMeshRegions.$n" \
-                splitMeshRegions -overwrite -cellZonesOnly || exit 1
-
-            # Remove cellToRegion
-            rm -f '0/cellToRegion' > /dev/null 2>&1
-            rm -f 'constant/cellToRegion' > /dev/null 2>&1
-# TODO [Low]: Recreate boundaryRegionAddressing for all regions
+        # Restore cellSets for this step of splitMeshRegions
+        for region in $regionlist; do
+            cp "constant/polyMesh/sets/bak/cellSet_$region" \
+            'constant/polyMesh/sets/' || exit 1
         done
 
         # Remove all zones
@@ -157,8 +120,8 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
         rm -f 'constant/polyMesh/faceZones' > /dev/null 2>&1
         rm -f 'constant/polyMesh/pointZones' > /dev/null 2>&1
 
-        # Create zones for all topoSets
-        runApplication \
+        # Create zones for restored topoSets
+        runApplication -l "log.setsToZones.$n" \
             setsToZones || exit 1
 
         # Remove topoSet prefixes from topoZones
@@ -166,69 +129,96 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
         sed -i 's/faceSet_//g' 'constant/polyMesh/faceZones' > /dev/null 2>&1
         sed -i 's/pointSet_//g' 'constant/polyMesh/pointZones' > /dev/null 2>&1
 
-        # Add fields to 0 from org backup
-        addZeroOrg
+        # Restore all topoSets
+        cp 'constant/polyMesh/sets/bak/'* \
+            'constant/polyMesh/sets/' \
+            > /dev/null 2>&1
 
-        # Move polyMesh from 0 to constant
-        # for regions
-        for region in $regionlist_split; do
-            moveZeroToConstantPolyMesh "$region"
-        done
+        # Split regions
+        runApplication -l "log.splitMeshRegions.$n" \
+            splitMeshRegions -overwrite -cellZonesOnly || exit 1
 
-        # Recreate topoSets from zones
-        # for regions
-        for region in $regionlist_split; do
-            runApplication -r "$region" \
-                zonesToSets -region "$region" || exit 1
-        done
+        # Remove cellToRegion
+        rm -f '0/cellToRegion' > /dev/null 2>&1
+        rm -f 'constant/cellToRegion' > /dev/null 2>&1
+# TODO [Low]: Recreate boundaryRegionAddressing for all regions
+    done
 
-        # Create new patches and cleanup
-        # for regions
-        for region in $regionlist_split; do
-            runApplication -r "$region" \
-                createPatch -overwrite -region "$region" || exit 1
+    # Remove all zones
+    rm -f 'constant/polyMesh/cellZones' > /dev/null 2>&1
+    rm -f 'constant/polyMesh/faceZones' > /dev/null 2>&1
+    rm -f 'constant/polyMesh/pointZones' > /dev/null 2>&1
 
-            rm "0/$region/cellToRegion" > /dev/null 2>&1
-            rm "constant/$region/polyMesh/boundaryRegionAddressing" > /dev/null 2>&1
-        done
+    # Create zones for all topoSets
+    runApplication \
+        setsToZones || exit 1
+
+    # Remove topoSet prefixes from topoZones
+    sed -i 's/cellSet_//g' 'constant/polyMesh/cellZones' > /dev/null 2>&1
+    sed -i 's/faceSet_//g' 'constant/polyMesh/faceZones' > /dev/null 2>&1
+    sed -i 's/pointSet_//g' 'constant/polyMesh/pointZones' > /dev/null 2>&1
+
+    # Add fields to 0 from org backup
+    addZeroOrg
+
+    # Move polyMesh from 0 to constant
+    # for regions
+    for region in $regionlist_split; do
+        moveZeroToConstantPolyMesh "$region"
+    done
+
+    # Recreate topoSets from zones
+    # for regions
+    for region in $regionlist_split; do
+        runApplication -r "$region" \
+            zonesToSets -region "$region" || exit 1
+    done
+
+    # Create new patches and cleanup
+    # for regions
+    for region in $regionlist_split; do
+        runApplication -r "$region" \
+            createPatch -overwrite -region "$region" || exit 1
+
+        rm "0/$region/cellToRegion" > /dev/null 2>&1
+        rm "constant/$region/polyMesh/boundaryRegionAddressing" > /dev/null 2>&1
+    done
 
 # TODO [Low]: Fix boundaryRegionAddressing for all regions
 # TODO [Low]: Fix cellToRegion for all regions
 
-        # Change dictionaries
-        # for regions
-        for region in $regionlist_split; do
-            runApplication -r "$region" \
-                changeDictionary -region "$region" || exit 1
-        done
+    # Change dictionaries
+    # for regions
+    for region in $regionlist_split; do
+        runApplication -r "$region" \
+            changeDictionary -region "$region" || exit 1
+    done
 
-        # Add fields to 0 from org backup
-        # for regions
-        for region in $regionlist_split; do
-            addZeroOrg "$region"
-        done
+    # Add fields to 0 from org backup
+    # for regions
+    for region in $regionlist_split; do
+        addZeroOrg "$region"
+    done
 
 # TODO [High]: Realize this without funkySetFields?
 
-        runApplication \
-            funkySetFields -time '0' || exit 1
+    runApplication \
+        funkySetFields -time '0' || exit 1
 
-        # Init turbulence values for fluid region
-        runApplication \
-            initTurbulenceValues -region 'region_fluid' || exit 1
+    # Init turbulence values for fluid region
+    runApplication \
+        initTurbulenceValues -region 'region_fluid' || exit 1
 
-        # Create finite area mesh for fluid region
-        restoreFaMeshOrg 'region_fluid'
-        runApplication -r 'region_fluid' \
-            makeFaMesh -region 'region_fluid' || exit 1
+    # Create finite area mesh for fluid region
+    restoreFaMeshOrg 'region_fluid'
+    runApplication -r 'region_fluid' \
+        makeFaMesh -region 'region_fluid' || exit 1
 
-        # Touch paraFoam files
-        paraviewTouchOpenFOAM
-        for region in $regionlist_split; do
-            paraviewTouchOpenFOAM "$region"
-        done
-
-    fi
+    # Touch paraFoam files
+    paraviewTouchOpenFOAM
+    for region in $regionlist_split; do
+        paraviewTouchOpenFOAM "$region"
+    done
 
     if [[ $flagParallel -eq 1 ]]; then
 
@@ -241,6 +231,20 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
         for region in $regionlist_split; do
             runApplication -r "$region" \
                 decomposePar -region $region || exit 1
+        done
+
+        # Decompose sets
+        # for regions
+        for region in $regionlist_split; do
+            runApplication -r "$region" \
+                decomposeSets -region $region || exit 1
+        done
+
+        # Decompose region addressings
+        # for regions
+        for region in $regionlist_split; do
+            runApplication -r "$region" \
+                decomposeRegionAddressing -region $region || exit 1
         done
 
         # Touch paraFoam files
