Fix overwrite option in splitMeshRegions. Minor fixes in tutorials. Drive inductionBlock3D towards interTrackEddyCurrentFoam

diff --git a/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/inductionBlock3D/Allrun b/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/inductionBlock3D/Allrun
--- a/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/inductionBlock3D/Allrun
+++ b/pascal-4.0/tutorials/surfaceTracking/newInterTrackEddyCurrentFoam/inductionBlock3D/Allrun
@@ -24,7 +24,10 @@ done
 
 setErrorTrap
 
-regionlist="region_conductor"
+regionlist_splitn=2
+regionlist_split1="region_fluid region_buffer region_static"
+regionlist_split2="region_conductor region_space"
+regionlist="$regionlist_split1 $regionlist_split2"
 
 if [[ $flagClean -eq 1 ]]; then
 
@@ -50,7 +53,7 @@ fi
 
 if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
 
-    # Restore polymesh from org backup
+    # Restore polymesh folder from org backup
     restorePolyMeshOrg
 
     # Remove all sets and zones
@@ -68,27 +71,51 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
     runApplication \
         changeDictionary || exit 1
 
-    # Create subset meshes
-    # for regions
-    for region in $regionlist; do
+    # Create backup of topoSets
+    rm "constant/polyMesh/sets/"*"_old" > /dev/null 2>&1
+    mkdir 'constant/polyMesh/sets/bak'
+    cp 'constant/polyMesh/sets/'* \
+        'constant/polyMesh/sets/bak/' \
+        > /dev/null 2>&1
 
-        runApplication -r "$region" \
-            subsetMesh "cellSet_$region" -overwrite || exit 1
+    # Create meshes
+    for n in $(eval echo "{1..$regionlist_splitn}"); do
 
-        mkdir 'constant/setSubset' > /dev/null 2>&1
-        mkdir 'constant/setSubset/polyMesh' > /dev/null 2>&1
-        mv "0/setSubset/polyMesh/"* "constant/setSubset/polyMesh/"
-        mkdir "constant/$region" > /dev/null 2>&1
-        mkdir "constant/$region/polyMesh" > /dev/null 2>&1
-        mv "constant/setSubset/polyMesh/"* "constant/$region/polyMesh"
-        rm -rf "0/setSubset"
-        rm -rf "constant/setSubset"
-        rm -rf "system/setSubset"
+        regionlist_split=$(eval echo \$regionlist_split$n)
 
-        runApplication -r "$region" \
-            createPatch -region "$region" -overwrite || exit 1
+        # Remove all topoSets
+        rm 'constant/polyMesh/sets/'* > /dev/null 2>&1
+
+        # Restore cellSets for this step of splitMeshRegions
+        for region in $regionlist_split; do
+            cp "constant/polyMesh/sets/bak/cellSet_$region" \
+            'constant/polyMesh/sets/' || exit 1
+        done
+
+        # Remove all zones
+        cleanPolyMeshZones
+
+        # Create zones for restored topoSets
+        runApplication -l "log.setsToZones.$n" \
+            setsToZones || exit 1
+
+        # Remove cellSet prefixes from cellZones
+        sed -i 's/cellSet_//g' 'constant/polyMesh/cellZones' > /dev/null 2>&1
+
+        # Split regions
+        runApplication -l "log.splitMeshRegions.$n" \
+            splitMeshRegions -overwrite -cellZonesOnly || exit 1
+
+        # Remove cellToRegion and cellZones
+        find -name 'cellToRegion' -delete > /dev/null 2>&1
+        find -name 'cellZones' -delete > /dev/null 2>&1
 
     done
+
+    # Restore all topoSets
+    cp 'constant/polyMesh/sets/bak/'* \
+        'constant/polyMesh/sets/' \
+        > /dev/null 2>&1
 
     # Add fields to 0 from org backup
     addZeroOrg
@@ -99,14 +126,63 @@ if [[ $flagPrepare -eq 1 && $flagClean -eq 1 ]]; then
         moveZeroToConstantPolyMesh "$region"
     done
 
+    # Create sets
+    # for regions
+    for region in $regionlist; do
+        runApplication -r "$region" \
+            makeRegionSets -region "$region" || exit 1
+    done
+
+    # Create new patches and cleanup
+    # for regions
+    for region in $regionlist; do
+        runApplication -r "$region" \
+            createPatch -overwrite -region "$region" || exit 1
+
+#         rm "constant/$region/polyMesh/boundaryRegionAddressing" > /dev/null 2>&1
+# TODO [Low]: Fix boundaryRegionAddressing for all regions
+    done
+
+    # Change dictionaries
+    # for regions
+    for region in $regionlist; do
+        runApplication -r "$region" \
+            changeDictionary -region "$region" || exit 1
+    done
+
     # Add fields to 0 from org backup
     # for regions
     for region in $regionlist; do
         addZeroOrg "$region"
     done
 
+    # Change fields according to funkySetFieldsDict
     runApplication \
         funkySetFields -time '0' || exit 1
+
+    # Init turbulence values for fluid region
+    runApplication \
+        initTurbulenceValues -region 'region_fluid' || exit 1
+
+    # Create finite area mesh for fluid region
+    restoreFaMeshOrg 'region_fluid'
+    runApplication -r 'region_fluid' \
+        makeFaMesh -region 'region_fluid' || exit 1
+
+    # Add faSubMesh to region list
+    regionlist="$regionlist region_fluid_faSubMesh"
+
+    # Clean old faSubMesh
+    cleanPolyMesh 'region_fluid_faSubMesh'
+
+    # Create faSubMesh
+    runApplication -r 'region_fluid' \
+        makeFaSubMesh -region 'region_fluid' || exit 1
+
+    # Create cell set for faSubMesh
+    runApplication -r 'region_fluid_faSubMesh' \
+        makeCellSetFromRegion -region 'region_fluid_faSubMesh' \
+            -cellSetName 'cellSet_region_fluid_faSubMesh' || exit 1
 
     # Touch paraFoam files
     paraviewTouchFoam
